const languages = [
    "English (US)",
    "Korean (한국어)",
    "Spanish (Spain)",
    "French (France)",
    "German (Germany)",
    "Italian (Italy)",
    "Portuguese (Portugal)",
    "Russian",
    "Chinese (Simplified) (中文)",
    "Japanese (日本語)",
    "Arabic (العربية)",
    "Hindi (हिन्दी)",
    "Bengali (বাংলা)",
    "Dutch (Netherlands)",
    "Turkish (Türkçe)",
    "Vietnamese (Tiếng Việt)",
    "Polish (Polski)",
    "Ukrainian (Українська)",
    "Thai (ไทย)",
    "Indonesian ",
    "Filipino (Tagalog)",
    "Romanian (Română)",
    "Greek (Ελληνικά)",
    "Czech (Čeština)",
    "Swedish (Svenska)",
    "Hungarian (Magyar)",
    "Danish (Dansk)",
    "Finnish (Suomi)",
    "Norwegian (Bokmål) ",
    "Hebrew (עברית)",
    "Malay (Bahasa Melayu)",
    "Slovak (Slovenčina)",
    "Croatian (Hrvatski)",
    "Tamil (தமிழ்)",
    "Bulgarian (Български)",
    "Slovenian (Slovenščina)",
    "Lithuanian (Lietuvių)",
    "Latvian (Latviešu)",
    "Estonian (Eesti)",
    "Serbian (Српски)",
    "Persian (فارسی)",
    "Urdu (اردو)",
    "Swahili (Kiswahili)",
    "Nepali (नेपाली)",
    "Icelandic (Íslenska)",
    "Georgian (ქართული)",
    "Armenian (Հայերեն)",
    "Sinhala (සිංහල)",
    "Kurdish  (کورمانجی)",
    "Pashto (پښتو)",
    "Hausa (Hausa)",
    "Zulu (isiZulu)",
    "Amharic (አማርኛ)",
    "Somali (Soomaali)",
    "Malagasy (Malagasy)",
    "Mongolian (Монгол)",
    "Uzbek (Oʻzbek)",
    "Javanese (Jawa)",
    "Igbo (Igbo)",
    "Yoruba (Yorùbá)",
    "Oromo (Oromoo)",
    "Fula (Fulfulde)",
    "Akan (Akan)",
    "Kazakh (Қазақ)",
    "Sunda (Basa Sunda)",
    "Tajik (Тоҷик)",
    "Azerbaijani (Azərbaycan)",
    "Kirundi (Kirundi)",
    "Kinyarwanda (Kinyarwanda)",
    "Tigrinya (ትግርኛ)",
    "Sesotho (Sesotho)",
    "Haitian Creole ",
    "Maltese (Malti)",
    "Burmese (မြန်မာ)",
    "Chichewa (Chichewa)",
    "Dhivehi (ދިވެހި)",
    "Tswana (Setswana)",
    "Shona (Shona)",
    "Maori (Māori)",
    "Hmong (Hmoob)",
    "Lingala (Lingála)",
    "Uyghur (Uyƣurqə)",
    "Mongolian (Cyrillic)",
    "Ewe (Ɛʋɛgbɛ)",
    "Samoan (Gagana Samoa)",
    "Tatar (Татар)",
    "Guarani (Avañe'ẽ)",
    "Kazakh (Cyrillic) (Қазақ)",
    "Tongan (Lea fakatonga)",
    "Xhosa (isiXhosa)",
    "Kikuyu (Gĩkũyũ)",
    "Quechua (Runa Simi)",
    "Tajik (Cyrillic) (Тоҷик)",
    "Cree (Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ)",
    "Luxembourgish (Lëtzebuergesch)",
    "Inuktitut (ᐃᓄᒃᑎᑐᑦ)",
    "Cherokee (ᏣᎳᎩ)",
    "Greenlandic (Kalaallisut)",
    "Galician (Galego)",
    "Basque (Euskara)",
    "Scots Gaelic (Gàidhlig)",
    "Manx (Gaelg)",
    "Faroese (Føroyskt)",
    "Corsican (Corsu)",
    "Frisian (Frysk)",
    "Aramaic (ܐܪܡܝܐ)",
    "Cornish (Kernewek)",
    "Breton (Brezhoneg)",
    "Sardinian (Sardu)",
    "Alsatian (Elsässisch)",
    "Lombard (Lumbaart)",
    "Venetian (Vèneto)",
    "Ligurian (Líguru)",
    "Friulian (Furlan)",
    "Romani (Romani)",
    "Papiamento (Papiamentu)",
    "Scots (Scots)",
    "Scots Gaelic (Gàidhlig)",
    "Welsh (Cymraeg)",
    "Irish (Gaeilge)",
    "Scottish Gaelic (Gàidhlig)",
    "Cornish (Kernewek)",
    "Breton (Brezhoneg)",
    "Manx (Gaelg)",
    "Faroese (Føroyskt)",
    "Greenlandic ",
    "Basque (Euskara)",
    "Catalan (Català)"
  ];
  
  export default languages;
  